const actionTypes = {
    STORE_BUBBLE_SORTED_RESULT: 'STORE_BUBBLE_SORTED_RESULT',
    IS_ALGO_RUNNING: 'IS_ALGO_RUNNING',
    SET_CURRENT_BUBBLETWO: 'SET_CURRENT_BUBBLETWO',
    SET_CURRENT_SWAPPERS: 'SET_CURRENT_SWAPPERS',
    SET_CURRENT_SORTED: 'SET_CURRENT_SORTED',
    SET_ARRAY: 'SET_ARRAY',
    SET_RUNNING: 'SET_RUNNING',
    SET_ALGORITHM: 'SET_ALGORITHM',
    SET_CURRENT_MERGEX: 'SET_CURRENT_MERGEX',
    SET_CURRENT_QUICKTWO: 'SET_CURRENT_QUICKTWO',
    SET_PIVOT: 'SET_PIVOT'
};

export default actionTypes;